insert into rodzaj_muzyki(nazwa)values('R&B');
insert into rodzaj_muzyki(nazwa)values('Blues');
insert into rodzaj_muzyki(nazwa)values('Country');
insert into rodzaj_muzyki(nazwa)values('Disco');
insert into rodzaj_muzyki(nazwa)values('Jazz');
insert into rodzaj_muzyki(nazwa)values('Punk');
insert into rodzaj_muzyki(nazwa)values('Reggae');
insert into rodzaj_muzyki(nazwa)values('Rock');
insert into rodzaj_muzyki(nazwa)values('Black metal');
insert into rodzaj_muzyki(nazwa)values('PoP');
insert into rodzaj_muzyki(nazwa)values('Death metal');
insert into rodzaj_muzyki(nazwa)values('Electronic rock');
insert into rodzaj_muzyki(nazwa)values('Flamenco');
insert into rodzaj_muzyki(nazwa)values('Funk rock');
insert into rodzaj_muzyki(nazwa)values('Gothic metal');
insert into rodzaj_muzyki(nazwa)values('Hardstyle');
insert into rodzaj_muzyki(nazwa)values('Hard house');
insert into rodzaj_muzyki(nazwa)values('Rap');
insert into rodzaj_muzyki(nazwa)values('Techno');
insert into rodzaj_muzyki(nazwa)values('');
insert into wykonawca(nazwa)values('Adele');
insert into wykonawca(nazwa)values('Coma');
insert into wykonawca(nazwa)values('Dzem');
insert into wykonawca(nazwa)values('Enej');
insert into wykonawca(nazwa)values('Lady Pank');
insert into wykonawca(nazwa)values('Blue Cafe');
insert into wykonawca(nazwa)values('Katy Perry');
insert into wykonawca(nazwa)values('Lady Gaga');
insert into wykonawca(nazwa)values('Rihanna');
insert into wykonawca(nazwa)values('Queen');
insert into wykonawca(nazwa)values('Nirvana');
insert into wykonawca(nazwa)values('Pearl Jam');
insert into wykonawca(nazwa)values('Coldplay');
insert into wykonawca(nazwa)values('Red Hot Chili Peppers');
insert into wykonawca(nazwa)values('The Rolling Stones');
insert into wykonawca(nazwa)values('The Beatles');
insert into wykonawca(nazwa)values('LMFAO');
insert into wykonawca(nazwa)values('U2');
insert into wykonawca(nazwa)values('Prince');
insert into wykonawca(nazwa)values('Bruce Springsteen');
insert into wykonawca(nazwa)values('Arcade Fire');
insert into wykonawca(nazwa)values(' Neil Young');
insert into wykonawca(nazwa)values('Jay Z');
insert into wykonawca(nazwa)values('Radiohead');
insert into wykonawca(nazwa)values('Jack White');
insert into wykonawca(nazwa)values('Rage Against the Machine');
insert into wykonawca(nazwa)values('My Morning Jacket');
insert into wykonawca(nazwa)values('The Black Keys');
insert into wykonawca(nazwa)values('Wilco');
insert into wykonawca(nazwa)values('Paul McCartney');
insert into wykonawca(nazwa)values('Alabama Shakes');
insert into wykonawca(nazwa)values('Metallica');
insert into wykonawca(nazwa)values('The Roots');
insert into wykonawca(nazwa)values('Kanye West');
insert into wykonawca(nazwa)values('Linkin Park');
insert into wykonawca(nazwa)values('Bee Gees');
insert into wykonawca(nazwa)values('Abba');
insert into wykonawca(nazwa)values('AC/DC');
insert into wykonawca(nazwa)values('Bon Jovi');
insert into wykonawca(nazwa)values('Depeche Mode');
insert into wykonawca(nazwa)values('One Direction');
insert into wykonawca(nazwa)values('Rammstein');
insert into wykonawca(nazwa)values('Scorpions');
insert into wykonawca(nazwa)values('Led Zeppelin');
insert into wykonawca(nazwa)values('Enigma');
insert into wykonawca(nazwa)values('Iron Maiden');